version: '3'

services:
  lua:
    build:
      context: .
      dockerfile: Dockerfile

  kong-database:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=53cr37

  kong:
    image: kong
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=53cr37
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    command: bash -c "sleep 5 && kong migrations up && kong start -v"
